# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'octopusenergy_exporter'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/src/Dockerfile'
        tags: 'latest'
        addPipelineData: false
        addBaseImageData: false